### ISSUE TITLE
♻️ Provide resolve-function for ExternalTasks

### ISSUE THREAD

**Issue by LeoTT** [process-engine/external_task_api_contracts#17]
#### Describe your issue

This applies to both c-sharp and typescript.
Right now you return values in tasks with a constructor call `new ExternalTaskFinished(externalTask.id, result)`.
Instead we could provide a resolve callback(as in js-promises). That way there is no extra import and the user does not need to remember to provide `externalTask.id`.

 https://github.com/process-engine/example_processes/blob/develop/solutions/ExternalTaskSample/external_task_worker/nodejs/index.js shows an example of usage. There is a function called handleTask in that example.

```js
  /* current implementation */
  const handleTask = async (externalTask) => {
    await sleep(20000);

    const result = {
      testproperty: 'Fertig',
      testproperty2: 10
    };
    return new ExternalTaskFinished(externalTask.id, result);
  };

  /* my preferred implementation */
  const myHandleTask = async (externalTask, resolve) => {
    await sleep(20000);

    const result = {
      testproperty: 'Fertig',
      testproperty2: 10,
    };
    resolve(result);
  };
```

#### Possible solution

Tested it with this gluecode:
```js
async function modifiedHandleTask(externalTask) {
  let result;
  const resolve = (callbackResult) => {
    result = callbackResult;
  }
  await myHandleTask(externalTask, resolve);
  return new ExternalTaskFinished(externalTask.id, result);
}
```
Can be improved for backwards compability.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@LeoTT In the future, please also create such issues in the runtime, because that is where we are collecting backend related issues. 

It is a good thing to have this issue here of course, because it affects both implementations, but for the sake of providing an easy overview over all .TS backend related issues, it'd be helpful to also have an issue for this at the runtime that links to this issue.

**Comment by ElRaptorus** [comment]
https://github.com/process-engine/process_engine_runtime/issues/109
